### ISSUE TITLE
Mouse cursor invisible

### ISSUE THREAD

**Issue by Frank973** [dottedmag/x2x#2]
Many thanks for your amazing and very interesting X2X.
I use it in original way and I have problem to see mouse cursor on the client machine.
Server is Ubuntu 10.4 with XRDP + TightVNC server
Client is tablet PC on Windows CE (sorry, no choice !) with RDP client
I use X2X over to the "to" display option, keyboard work, the mouse is active (II can focuse windows and clic R is active, ex: menu on desktop) but the mouse cursor is not visible. Only the original pointer from CE is visible and don't move.
I have try many options in x2x, rdp, vnc, x11, but it's seems to be outside of my competence .
Do you have some idea ?
Thanks Frank French Guiana

**Comment by luxigo** [comment]
For gnome or unity try 
```          gsettings set org.gnome.settings-daemon.plugins.cursor active false```
or
```          dconf write /org/gnome/settings/daemon/plugins/cursor/active false```

 and restart the session.

It solved the problem in my case, where the cursor was invisible until the real mouse was moved.

**Comment by purplehuman** [comment]
I have the same problem.

Unfortunately, luxigo's dconf trick didn't solve this problem for me.

**Comment by luxigo** [comment]
@ghost :If you are using it, you could try to switch from xserver-xorg-video-nouveau to the proprietary nvidia-xxx driver

**Comment by dottedmag** [comment]
Apologies for not responding for 10 years (!). Apparently my GitHub e-mails were turned off.

This project is dormant and is looking for a new maintainer. However, from the discussion, it seems that the problem was solved.

**Comment by aemonge** [comment]
Ten years....... you're right, but you also made me feel old :P
