### ISSUE TITLE
X2X can't move mouse to secondary screen if a primary window is too close to the edge after upgrade to Ubuntu 18.04

### ISSUE THREAD

**Issue by troyrock** [dottedmag/x2x#24]
Starting after upgrading to Ubuntu 18.04 from 16 (switching from the Unity desktop to the Gnome desktop), when I try to move the mouse to the right to my secondary screen it will stop at the edge of the screen if the primary screen has a window too close to the edge of the screen.  If the primary screen has a window maximized, for instance I can't move the mouse to the secondary screen until I un-maximize.  If a window  takes up the top half of the primary screen, I must move the mouse cursor over the right threshold on the bottom half of the screen to successfully move it to the secondary screen.  I'm sure that it has something to do with releasing the mouse cursor and possibly there is a work-around like making the 1 pixel wide x2x window "always on top" or something like that but I'm unsure how to do that.  Thanks for your help and for a wonderful tool.

**Comment by barak** [comment]
Could it be that the window blocking things is a Wayland window, so X (and hence x2x) are not seeing your mouse in it? To check, run xeyes and if those googly orbs stop following your mouse when it's in that window then it's a Wayland window. (The Gnome Settings window is a Wayland window, if you want to test.)

**Comment by troyrock** [comment]
The eyes continue to watch as I move up and down on the edge of the screen when a window is maximized and inside the Gnome settings window.

**Comment by barak** [comment]
So you're in Gnome-on-X mode rather than Gnome-on-Wayland mode? You can check with
```
$ printenv | egrep -i '(wayland|display|session_type)'
DISPLAY=:0
WAYLAND_DISPLAY=wayland-0
XDG_SESSION_TYPE=wayland
```
which, as you can see, shows that I'm running Wayland.

**Comment by troyrock** [comment]
DISPLAY:=1
WDG_SESSION_TYPE=x11

**Comment by bingtimren** [comment]
I have the same issue. 

$ printenv | egrep -i '(wayland|display|session_type)';
DISPLAY=:0
XDG_SESSION_TYPE=x11

**Comment by bingtimren** [comment]
And the environment is the same on both machines.

$ printenv | egrep -i '(wayland|display|session_type)'
DISPLAY=:0
XDG_SESSION_TYPE=x11

**Comment by bingtimren** [comment]
And maybe this (on my primary, i.e. controlling machine) may help?

$ ps ax|egrep -i '(xorg|wayland)'
 1500 tty1     Ssl+   0:00 /usr/lib/gdm3/gdm-wayland-session gnome-session --autostart /usr/share/gdm/greeter/autostart
 1613 tty1     Sl+    0:00 /usr/bin/Xwayland :1024 -rootless -terminate -accessx -core -listen 4 -listen 5 -displayfd 6
 2826 tty2     Sl+    6:43 /usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -background none -noreset -keeptty -verbose 3
11929 pts/1    S+     0:00 grep -E --color=auto -i (xorg|wayland)

**Comment by bingtimren** [comment]
I can further report that, when I place the secondary screen on south the mouse pointer can travel to the secondary screen even there's a full size window on the primary screen. So placing the secondary screen to the south with "-south" can be used as a walk around.

If I place the secondary screen to the north the mouse simply cannot travel to the secondary screen, apparently blocked by the title bar.

**Comment by bingtimren** [comment]
Just had another observation.

If I first launch a window (for example chrome browser) then run x2x, my mouse can travel across the border even if the window is full sized.

If I first run x2x then launch a window and make it full size, my mouse cannot travel across the border if the window is full sized.

**Comment by bingtimren** [comment]
Hi I solved this problem and submitted a pull request. Build from https://github.com/bingtimren/x2x and use with two new options -win-output and -win-transparent.
