### ISSUE TITLE
Broken lawyerese.c file breaks the build

### ISSUE THREAD

**Issue by yurivict** [dottedmag/x2x#27]
Contents of this file:

```
char *lawyerese =
; 
```

OS: FreeBSD 11.1

**Comment by barak** [comment]
This works for me, on Debian. Presumably the `lawyerese.c:` stanza in `Makefile.am` works with GNU Make but not with BSD Make. Here is what I get:
```
$ ./configure
$ rm lawyerese.c 
$ make lawyerese.c 
echo 'char *lawyerese =' > lawyerese.c.tmp && \
	sed -e 's|.*|"\0\\n"|g' COPYING >> lawyerese.c.tmp && \
	echo ";" >> lawyerese.c.tmp && \
	mv lawyerese.c.tmp lawyerese.c || rm -f lawyerese.c.tmp
```
I'm guessing that the `$^` construct doesn't work? If that's the problem, it could be replaced with `$(COPYING_FILES)`. Anyway, a BSD-clean patch to that stanza would be welcome.

**Comment by yurivict** [comment]
I changed to GNU make in the port.
Thanks!
