### ISSUE TITLE
x2x: display names are both :0

### ISSUE THREAD

**Issue by edgecate** [dottedmag/x2x#34]
When I run the following command:
ssh -YC username@ip.address "x2x -west -to :0"

I get the following message and it doesn't connect:
x2x: display names are both :0

Any idea what the issue is and how to fix it?

**Comment by barak** [comment]
You're supposed to connect x2x to two different servers, one of which can be passed implicitly by the DISPLAY environment variable. They cannot be the same server, that would be like Russell's Paradox and could collapse the quantum vacuum and destroy the universe.

**Comment by edgecate** [comment]
Ah I get what you mean now - I misinterpreted the error.
