### ISSUE TITLE
The -resurface otion is not working

### ISSUE THREAD

**Issue by Marwen-BM** [dottedmag/x2x#38]
Hi,

When x2x windows are obscured by another window, they never come back upfront even when _-resurface_ or _-struts_ options are used.

I was able to fix the issue by setting the class of the x2x windows to **InputOutput** instead of **InputOnly** (at x2x.c:1270).
InputOnly windows never receive the VisibilityNotify event, thus the ProcessVisibility() callback is never called.
Xlib documentation confirming : https://tronche.com/gui/x/xlib/events/window-state-change/visibility.html

**Comment by barak** [comment]
Make a pull request with this info in the commit log and I'll pull it.

**Comment by Marwen-BM** [comment]
Done
