### ISSUE TITLE
keys not working /characters missing

### ISSUE THREAD

**Issue by ghost** [dottedmag/x2x#4]
Hello there, 
x2x is really an amazing tool!! I love it, however some of my keys are not workikng, I have in both sides an english international keyboard and there are some keys that do not work on remote node: ", ', ´, `, ~
unfortunately there's no error output ...
I'm using ubuntu maverik and debian lenny, both with the repository version of x2x.
thanks!!

**Comment by barak** [comment]
@lkraav Thanks for the comment, I've added it to the man page x2x(1).

**Comment by oscarfv** [comment]
I'm also using a US International With Dead Keys layout and suffered the same problem. In the process of evaluating other tools (synergy) I added the Spanish keymap too. Then tried `x2x` and it got more keys right when the remote machine was set to use the Spanish keymap. When the US keymap was selected it was a mess. Then uninstalled the Spanish layout and surprisingly this fixed the problem. Now the the US keymap seems to work fine.

So make sure that the output of `setxkbmap -query` is identical on both machines.

**Comment by barak** [comment]
added this to man page, commit 64f0bfb

**Comment by morngrar** [comment]
For anyone encountering this issue, and have identical output from `setxkbmap -query` but are still encountering it. If your setup involves toggling between different keymaps on the machines (for example if you have one toggle for nodeadkeys or not), make sure that the toggle is in the same state on both machines.

**Comment by morngrar** [comment]
> For anyone encountering this issue, and have identical output from `setxkbmap -query` but are still encountering it. If your setup involves toggling between different keymaps on the machines (for example if you have one toggle for nodeadkeys or not), make sure that the toggle is in the same state on both machines.

This was actually wrong. After a reboot the problem reappeared, and was fixed by running `setxkbmap` without arguments on the machine running x2x from the controlling machine

**Comment by barak** [comment]
Be great to have this documented...
