### ISSUE TITLE
Question : Can I control a windows with this ?

### ISSUE THREAD

**Issue by QuentinN42** [dottedmag/x2x#40]
I want to have one keyboard on my office and control multiples computers, can I use x2x to control windows machines or is it only for linux ?

There is a mention of windows in the readme but no executables or tutorials for windows :weary: 

Thanks in advance :heart:

**Comment by barak** [comment]
MS Windows? I wouldn't think so. In fact, with Wayland ascendant, I don't think you can even really control Linux with it anymore.

**Comment by mmfrank** [comment]
Take a look at **x2vnc**.  I use this to remote control a Windows laptop.  It is necessary to install a VNC server on the Windows side.

**Comment by dottedmag** [comment]
Looks like the question is answered to everyone's satisfaction.
