### ISSUE TITLE
clipboard not shared 

### ISSUE THREAD

**Issue by rmosse** [dottedmag/x2x#7]
clipboard not shared. tested in ubuntu 12.04

**Comment by archenemies** [comment]
I can confirm this on Arch Linux!

**Comment by purplehuman** [comment]
Actually it is shared, I tried it with two Ubuntu computers. But normal shortcuts or right-click paste commands don't work. You need to paste with middle click. That way it works.

**Comment by towc** [comment]
some of us don't have a middle click :/

**Comment by BETLOG** [comment]
I have a middle click, and can't get ANY form of copy/paste to work.
Mind you; despite having xclip working previously (before I discovered x2x), it also refuses to work at all now.

`setsid x2x -to betlognuc:0 -south `

Kubuntu 18.04
```
uname -a
Linux betlogbrick 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
```
netstat -an | grep -F 6000
tcp        0      0 0.0.0.0:6000            0.0.0.0:*               LISTEN     
tcp6       0      0 :::6000                 :::*                    LISTEN     
tcp6       0      0 2001:44b8:2124:f0:42660 2001:44b8:2124:f00:6000 ESTABLISHED
```

Kubuntu 14.04
```
uname -a
Linux betlognuc 3.13.0-170-generic #220-Ubuntu SMP Thu May 9 12:40:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
netstat -an | grep -F 6000
tcp        0      0 0.0.0.0:6000            0.0.0.0:*               LISTEN     
tcp6       0      0 :::6000                 :::*                    LISTEN     
tcp6       0      0 2001:44b8:2124:f00:6000 2001:44b8:2124:f0:42660 ESTABLISHED
```

**Comment by dottedmag** [comment]
It seems that the X clipboard (`PRIMARY` selection) is shared, but `CLIPBOARD`, this is covered in #19.
